fail_fast: true

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.5
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
        additional_dependencies: [tokenize-rt]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1024']
      - id: check-executables-have-shebangs
        files: \.(py|sh)$
      - id: check-docstring-first
        files: \.(py)$
        exclude: |
            (?x)^(
                scratch.py
            )$
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
        files: \.(py|sh)$
      - id: check-symlinks
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
        files: \.(py|sh)$
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        files: \.(py|sh)$
      - id: requirements-txt-fixer
        files: requirements.txt
      - id: check-toml
        files: \.toml$
      - id: check-yaml
        args: [--unsafe]
        files: \.(yaml|yml)$
      - id: pretty-format-json
        # https://pre-commit.com/#regular-expressions
        args: ['--autofix', '--indent=2', '--no-sort-keys']
        files: \.(json|jsonc)$
        exclude: |
            (?x)^(
                .devcontainer/devcontainer.json|
                .vscode/launch.json|
                .vscode/settings.json|
                .vscode/extensions.json|
            )$
